/// Flutter icons Custom2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom2
///      fonts:
///       - asset: fonts/Custom2.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom2 {
  Custom2._();

  static const _kFontFam = 'Custom2';
  static const _kFontPkg = null;

  static const IconData truffle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData growing_weed = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData insecticide = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virus = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant__2_ = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lavender = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plant__3_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fertilizer = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData healthy_food = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sprayer = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData electric_motor__1_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technical_support = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData agriculture = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData technology = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
