/// Flutter icons Custom3
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Custom3
///      fonts:
///       - asset: fonts/Custom3.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Custom3 {
  Custom3._();

  static const _kFontFam = 'Custom3';
  static const _kFontPkg = null;

  static const IconData dairy_products = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData milk = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hen = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chicken__1_ = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData protect = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fish_net = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farming = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hose = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData greenhouse = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cultivation = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData road_roller = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor__1_ = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor__3_ = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tractor__6_ = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weeder = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData barn = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
